grid = [
    [
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 6, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 5, "init": True},
        {"num": None, "init": False},
        {"num": 8, "init": True},
    ],
    [
        {"num": 1, "init": True},
        {"num": None, "init": False},
        {"num": 2, "init": True},
        {"num": 3, "init": True},
        {"num": 8, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 4, "init": True},
    ],
    [
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 2, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 1, "init": True},
        {"num": 9, "init": True},
        {"num": None, "init": False},
    ],
    [
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 6, "init": True},
        {"num": 3, "init": True},
        {"num": None, "init": False},
        {"num": 4, "init": True},
        {"num": 5, "init": True},
    ],
    [
        {"num": None, "init": False},
        {"num": 6, "init": True},
        {"num": 3, "init": True},
        {"num": 4, "init": True},
        {"num": None, "init": False},
        {"num": 5, "init": True},
        {"num": 8, "init": True},
        {"num": 7, "init": True},
        {"num": None, "init": False},
    ],
    [
        {"num": 5, "init": True},
        {"num": 4, "init": True},
        {"num": None, "init": False},
        {"num": 9, "init": True},
        {"num": 2, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
    ],
    [
        {"num": None, "init": False},
        {"num": 8, "init": True},
        {"num": 7, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 4, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
    ],
    [
        {"num": 2, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 9, "init": True},
        {"num": 8, "init": True},
        {"num": 4, "init": True},
        {"num": None, "init": False},
        {"num": 7, "init": True},
    ],
    [
        {"num": 4, "init": True},
        {"num": None, "init": False},
        {"num": 9, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": None, "init": False},
        {"num": 3, "init": True},
        {"num": None, "init": False},
        {"num": None, "init": False},
    ],
]