# Generated by Django 4.2.11 on 2024-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuscan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='image',
        ),
        migrations.AddField(
            model_name='sudoku',
            name='image_data',
            field=models.TextField(default=''),
        ),
    ]
