# Generated by Django 4.2.11 on 2024-04-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuscan', '0002_remove_sudoku_image_sudoku_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=models.JSONField(),
        ),
    ]
